import React from "react";
import About from "../components/About";
// import { About } from '../components/About_us'
import { Anaheim, Inter, Roboto } from "@next/font/google";

import { Footer, Header } from "../components/common";
import Head from "next/head";
const roboto = Anaheim({
  weight: "400",
  subsets: ["latin"],
});
function about() {
  return (
    <div>
      <Head>
        <title>About us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main className={roboto.className}>
        <Header />
        <About />
        <Footer />
      </main>
    </div>
  );
}

export default about;
