import Head from "next/head";
import React from "react";
import Detail from "../../../components/product/detail";
import { sentslugRequest } from "../../../redux/product";
import { wrapper } from "../../../store";

function Product() {
  return (
    <>
      <Head>
        <title>Product Detail</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
        <Detail />
      </main>
    </>
  );
}

export default Product;

export const getStaticPaths = async () => {
  return {
    paths: [],
    fallback: true,
  };
};

export const getStaticProps = wrapper.getStaticProps((store) => async (ctx) => {
  if (ctx?.params?.id) {
    // await store.dispatch(sentslugRequest(ctx?.params?.id));
  }
  // await store.dispatch(navDataRequest());
  // await store.dispatch(footerDataRequest());
});
