import Head from 'next/head';
import React from 'react'
import { Anaheim, Inter, Roboto } from '@next/font/google'
import { Footer, Header } from '../../components/common';
import Subproduct from '../../components/main_products/Subproduct';
import { productDataRequest } from '../../redux/home';
import { wrapper } from '../../store';
const roboto = Anaheim({
  weight: '400',
  subsets: ['latin'],
})
function Product() {
  return (
    <>
    <Head>
    <title>Products</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/images/logo.png" />
  </Head>
  <main className={roboto.className}>
    <Header/>
   <Subproduct/>
    <Footer/>
  </main>
    </>
  )
}

export default Product;
// export const getStaticPaths = async () => {
//   return {
//     paths: [],
//     fallback: true,
//   };
// };

export const getServerSideProps = wrapper.getServerSideProps((store) => async (ctx) => {
  if (ctx?.params?.id) {
    // await store.dispatch(sentslugRequest(ctx?.params?.id));
  }
  await store.dispatch(productDataRequest ());
  // await store.dispatch(navDataRequest());
  // await store.dispatch(footerDataRequest());
});